Test dialog
isaacy13/arbalest pull request #8
Opened 2022-10-25 01:47 UTC by alvin0703

Able to register select all suite check option clicked

2022-10-25 01:52 UTC, alvin0703 commented
Update TestsSuites table in db to TestSuites
Correct error where one test suite have more than 1 test suite id
Provide a select all option and a check list for test suite selection in test dialog
Provide a select all option and a check list for test selection in test dialog
Register select all option clicked under test suite selection

2022-10-25 02:49 UTC, daperego approved these changes

2022-10-25 04:25 UTC, isaacy13 requested changes
finished code review -- need to actually test

2022-10-25 04:25 UTC, isaacy13 commented on src/gui/VerificationValidationWidget.cpp
> +void VerificationValidationWidget::updateUI() {
is this event necessary for the future? 
- since it's only printing stuff right now

and if it is necessary, do we need to call super.updateUI()?
- in C++ I think it'd be QHBoxWidget::updateUI()

2022-10-25 04:25 UTC, isaacy13 commented on src/gui/VerificationValidationWidget.cpp
> +	std::cout << "Branch: testDialog" << std::endl;
maybe remove debug output for dev branch? optional

2022-10-27 22:12 UTC, isaacy13 commented on src/gui/VerificationValidationWidget.cpp
> +void VerificationValidationWidget::updateUI() {
done by alvin

2022-10-27 22:24 UTC, closed without merging