Gqa parser
isaacy13/arbalest pull request #9
Opened 2022-10-25 02:09 UTC by daperego

Recreated gqa parser to have consistency with search parser's format. May not parse as intended currently, but will compile.

2022-10-25 03:01 UTC, isaacy13 requested changes
finished review

2022-10-25 03:01 UTC, isaacy13 commented on src/gui/VerificationValidationWidget.cpp
> +        if (QString::compare(executableName, "gqa", Qt::CaseInsensitive) == 0)
ideally have this as "else if" to prevent unnecessary comparisons

2022-10-25 03:01 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +    if (currentLine.trimmed().startsWith("Trying initial grid spacing", Qt::CaseInsensitive) == true ||
would it be possible to avoid these checks?
- e.g.: maybe we only call gqaSpecificTest() on lines after "list Overlaps:"?
- mainly for runtime; not too bad when currentLine is small, but runtimes can add up, especially when trimming and looking for case insensitive .startsWith() each time

2022-10-25 03:01 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +        QString objectName1 = objectPath1.mid(objectPath1.lastIndexOf('/'), objectPath1.size() - objectPath1.lastIndexOf('/'));
about using .lastIndexOf() here:
- is it possible for the line to just have the object? (e.g.: "object.r", no slashes)
- i did this same thing and ran into parsing issues whenever there was no '/', but it was a valid object

2022-10-25 03:01 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +    if(type == &DefaultTests::NO_OVERLAPS)
preferrably change to else if -- type can only be one of them

2022-10-25 03:01 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +        QString objectName1 = objectPath1.mid(objectPath1.lastIndexOf('/'), objectPath1.size() - objectPath1.lastIndexOf('/'));
same thing here and below as previously with the .lastIndexOf()

2022-10-25 03:01 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +        QString objectPath2 = currentLine.split(' ')[1];
could we save the .split() result and get the indexes only once?
- runtime/resource intensive
- maybe something like 
`QStringList objectList = currentLine.split(' ');`
`QString objectPath1 = objectList[0];`
`QString countString = objectList[2];`
etc... with all, so don't do same workload repeatedly

2022-10-25 03:46 UTC, daperego commented on src/utils/VerificationValidationParser.cpp
> +    if (currentLine.trimmed().startsWith("Trying initial grid spacing", Qt::CaseInsensitive) == true ||
Avoided by checking for first meaningful line.

2022-10-25 03:47 UTC, daperego commented on src/utils/VerificationValidationParser.cpp
> +        QString objectName1 = objectPath1.mid(objectPath1.lastIndexOf('/'), objectPath1.size() - objectPath1.lastIndexOf('/'));
Fixed.

2022-10-25 03:47 UTC, daperego commented on src/utils/VerificationValidationParser.cpp
> +    if(type == &DefaultTests::NO_OVERLAPS)
Fixed.

2022-10-25 03:47 UTC, daperego commented on src/utils/VerificationValidationParser.cpp
> +        QString objectName1 = objectPath1.mid(objectPath1.lastIndexOf('/'), objectPath1.size() - objectPath1.lastIndexOf('/'));
Fixed.

2022-10-25 03:47 UTC, daperego commented on src/utils/VerificationValidationParser.cpp
> +        QString objectPath2 = currentLine.split(' ')[1];
Fixed.

2022-10-25 03:47 UTC, daperego commented on src/gui/VerificationValidationWidget.cpp
> +        if (QString::compare(executableName, "gqa", Qt::CaseInsensitive) == 0)
Fixed.

2022-10-25 04:32 UTC, isaacy13 requested changes
need to pull test, but after that I'm good to approve

2022-10-25 04:32 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +        if(objectPath1.indexOf('/') != -1)
I know I'm being really nit-picky here, but:
- could we save result of .indexOf() into a variable so we don't repeatedly call it
- so like "if(resultIdx != -1) { objectName1 = objectPath1.mid(resultIdx, objectPath1.size() - resultIdx); }"

2022-10-28 00:17 UTC, isaacy13 submitted a review, later dismissed
looks good

2022-10-28 00:24 UTC, isaacy13 requested changes

2022-10-28 00:24 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +    return false;
this should be implemented in case user creates custom command and messes up syntax

2022-10-28 00:24 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +    return false;
should be implemented in case object doesn't exist in tree
- e.g.: if /all doesn't exist

2022-10-28 16:25 UTC, isaacy13 approved these changes

2022-10-31 23:30 UTC, isaacy13 requested changes

2022-10-31 23:30 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +    int msgStart = r->terminalOutput.indexOf(QRegExp("Search path error:\n input: '.*' normalized: '.* not found in database!'", Qt::CaseInsensitive));
db not found cannot be generalized; specific per command

2022-11-01 02:08 UTC, isaacy13 approved these changes

2022-11-04 18:12 UTC, isaacy13 requested changes

2022-11-04 18:12 UTC, isaacy13 commented on src/utils/VerificationValidationParser.cpp
> +        if(lines[i].startsWith("list Overlaps"))
bug in demo with Sean

2022-11-04 22:16 UTC, daperego commented on src/utils/VerificationValidationParser.cpp
> +        if(lines[i].startsWith("list Overlaps"))
Fixed

2022-11-04 23:18 UTC, isaacy13 requested changes
![image](https://user-images.githubusercontent.com/65752735/200088137-c91f0269-dfed-4a7d-8096-89a1f1e219df.png)
looks good to me, but last thing:
- only objectName is displayed, not objectPath

2022-11-05 01:19 UTC, isaacy13 approved these changes

2022-11-05 01:19 UTC, merged